name: Scale
version: "${pom.version}"
api: ["1.0.0"]
author: PetteriM1
main: idk.plugin.scale.Main

commands:
  scale:
    description: Change your size
    usage: "/scale <size>"
    permission: scale.edit

permissions:
  scale.edit:
    description: "Allows player to use /scale"
    default: op
